UI/WebStore/Areas/Admin/Controllers/CatalogController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebStore.Domain.Entities;
using WebStore.Domain.Entities.Identity;
using WebStore.Interfaces.Services;

namespace WebStore.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize(Roles = Role.Administrator)]
    public class CatalogController : Controller
    {
        private readonly IProductData _ProductData;

        public CatalogController(IProductData ProductData) => _ProductData = ProductData;

        public IActionResult Index() => View(_ProductData.GetProducts());

        public IActionResult Edit(int id)
        {
            var product = _ProductData.GetProductById(id);
            if (product is null) return NotFound();
            return View(product);
        }

        [HttpPost]
        public IActionResult Edit(Product product)
        {
            if (!ModelState.IsValid) return View(product);
            
            // Логика редактирования
            // Логика вызова метода из IProductData

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var product = _ProductData.GetProductById(id);
            if (product is null) return NotFound();
            return View(product);
        }

        [HttpPost]
        public IActionResult DeleteConfirm(int id)
        {
            // Логика удаления

            return RedirectToAction(nameof(Index));
        }
    }
}

UI/WebStore/Components/BreadCrumbsViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebStore.Interfaces.Services;
using WebStore.ViewModels;

namespace WebStore.Components
{
    //Комнпонент "Хлебные крошки", показывающий где мы находимся
    public class BreadCrumbsViewComponent : ViewComponent
    {
        private readonly IProductData _productData;

        public BreadCrumbsViewComponent(IProductData productData)
        {
            _productData = productData;
        }

        public IViewComponentResult Invoke()
        {
            var viewModel = new BreadCrumbsViewModel();

            //Параметры секции и бренда лежат в строке запроса
            if (int.TryParse(Request.Query["SectionId"], out var sectionId))
            {
                viewModel.Section = _productData.GetSectionById(sectionId);
                var parentSectionId = viewModel.Section?.ParentId;
                if (parentSectionId != null)
                    viewModel.MasterSection = _productData.GetSectionById(parentSectionId.Value);
            }

            if (int.TryParse(Request.Query["BrandId"], out var brandId))
                viewModel.Brand = _productData.GetBrandById(brandId);

            //Информация о товаре лежат в другом месте: в маршруте
            if (int.TryParse(ViewContext.RouteData.Values["id"]?.ToString(), out var productId))
                viewModel.Product = _productData.GetProductById(productId)?.Name;

            return View(viewModel);
        }
    }
}

UI/WebStore/Controllers/CatalogController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WebStore.Domain;
using WebStore.Interfaces.Services;
using WebStore.Services.Mapping;
using WebStore.Domain.ViewModels;
using Microsoft.Extensions.Configuration;

namespace WebStore.Controllers
{
    public class CatalogController : Controller
    {
        private readonly IProductData _productData;
        private readonly IConfiguration _configuration;

        public CatalogController(IProductData productData, IConfiguration configuration)
        {
            _productData = productData;
            _configuration = configuration;
        }

        public IActionResult Shop(int? BrandId, int? SectionId, int Page = 1, int? PageSize = null)
        {
            var pageSize = PageSize ?? (int.TryParse(_configuration["CatalogPageSize"], out var value) ? value : null);
            var pageProducts = _productData.GetProducts(new ProductFilter
            {
                BrandId = BrandId,
                SectionId = SectionId,
                Page = Page,
                PageSize = pageSize,
            });

            var model = new CatalogViewModel()
            {
                SectionId = SectionId,
                BrandId = BrandId,
                Products = pageProducts.Products.OrderBy(p => p.Order).ToView(),
                PageViewModel = new PageViewModel
                {
                    PageNumber = Page,
                    PageSize = pageSize ?? 0,
                    TotalItems = pageProducts.TotalCount,
                }
            };
            return View(model);
        }

        public IActionResult Shop2(ProductFilter filter)
        {
            var products = _productData.GetProducts(filter);

            return View("Shop", new CatalogViewModel
            {
                SectionId = filter.SectionId,
                BrandId = filter.BrandId,
                Products = products.Products
                   .OrderBy(p => p.Order)
                   .Select(p => new ProductViewModel
                    {
                        Id = p.Id,
                        Name = p.Name,
                        Price = p.Price,
                        ImageUrl = p.ImageUrl
                    })
            });
        }
        
        public IActionResult Details(int id)
        {
            var product = _productData.GetProductById(id);

            if (product is null)
                return NotFound();
            
            return View(product.ToView());
        }
    }
}

UI/WebStore/Views/Catalog/Details.cshtml
@model ProductViewModel
@{
    ViewData["Title"] = Model.Name;
}

<section>
    <div class="container">
        <vc:bread-crumbs />

        <div class="row">
            <div class="col-sm-3">
                <partial name="Partial/_LeftSideBar" />
            </div>

            <div class="col-sm-9 padding-right">
                <div class="product-details">
                    <!--product-details-->
                    <div class="col-sm-5">
                        <div class="view-product">
                            <img src="~/images/product-details/1.jpg" alt="" />
                            <h3>ZOOM</h3>
                        </div>
                        <div id="similar-product" class="carousel slide" data-ride="carousel">

                            <!-- Wrapper for slides -->
                            <div class="carousel-inner">
                                <div class="item active">
                                    <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                                </div>
                                <div class="item">
                                    <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                                </div>
                                <div class="item">
                                    <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                                </div>

                            </div>

                            <!-- Controls -->
                            <a class="left item-control" href="#similar-product" data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                            </a>
                            <a class="right item-control" href="#similar-product" data-slide="next">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>

                    </div>
                    <div class="col-sm-7">
                        <div class="product-information">
                            <!--/product-information-->
                            <img src="~/images/shop/@Model.ImageUrl" class="newarrival" alt="" />
                            <h2>@Model.Name</h2>
                            <p>Web ID: @Model.Id.ToString("00000000")</p>
                            <img src="~/images/product-details/rating.png" alt="" />
                            <span>
                                <span>@Model.Price.ToString("C")</span>
                                <label>Количество:</label>
                                <input type="text" value="3" />
                                <a asp-controller="Cart" 
                                   asp-action="AddToCart" 
                                   asp-route-id="@Model.Id"
                                   data-product-id="@Model.Id"
                                   class="btn btn-default cart add-to-cart">
                                    <i class="fa fa-shopping-cart"></i>
                                    В корзину
                                </a>
                            </span>
                            <p><b>Доступность:</b> На складе</p>
                            <p><b>Состояние:</b> Новое</p>
                            <p><b>Бренд:</b> @Model.Brand</p>
                            <a href="">
                                <img src="~/images/product-details/share.png" class="share img-responsive" alt="" />
                            </a>
                        </div><!--/product-information-->
                    </div>
                </div><!--/product-details-->

                <partial name="Partial/_CategoryTab" />

                <partial name="Partial/_RecomendedItems" />
            </div>
        </div>
    </div>
</section>

UI/WebStore/Views/Catalog/Shop.cshtml
@model CatalogViewModel
@{
    ViewData["Title"] = "Каталог товаров";
}


<partial name="Partial/_Advertisement"/>

<section>
    <div class="container">
        <vc:bread-crumbs />

        <div class="row">
            <div class="col-sm-3">
                <partial name="Partial/_LeftSideBar"/>
            </div>

            <div class="col-sm-9 padding-right">
                <partial name="Partial/_FeaturesItems" model="Model.Products"/>

                <paging page-model="@Model.PageViewModel" 
                        page-url-SectionId="@Model.SectionId"
                        page-url-BrandId="@Model.BrandId"
                        page-url-PageSize="@Context.Request.Query["PageSize"]"
                        page-action="Shop">

                </paging>
            </div>
        </div>
    </div>
</section>